-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity makeZero is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_0_ce0 : OUT STD_LOGIC;
    mat_0_we0 : OUT STD_LOGIC;
    mat_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_0_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_0_ce1 : OUT STD_LOGIC;
    mat_0_we1 : OUT STD_LOGIC;
    mat_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_1_ce0 : OUT STD_LOGIC;
    mat_1_we0 : OUT STD_LOGIC;
    mat_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_1_ce1 : OUT STD_LOGIC;
    mat_1_we1 : OUT STD_LOGIC;
    mat_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_2_ce0 : OUT STD_LOGIC;
    mat_2_we0 : OUT STD_LOGIC;
    mat_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_2_ce1 : OUT STD_LOGIC;
    mat_2_we1 : OUT STD_LOGIC;
    mat_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_3_ce0 : OUT STD_LOGIC;
    mat_3_we0 : OUT STD_LOGIC;
    mat_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_3_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_3_ce1 : OUT STD_LOGIC;
    mat_3_we1 : OUT STD_LOGIC;
    mat_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_4_ce0 : OUT STD_LOGIC;
    mat_4_we0 : OUT STD_LOGIC;
    mat_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_4_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_4_ce1 : OUT STD_LOGIC;
    mat_4_we1 : OUT STD_LOGIC;
    mat_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_5_ce0 : OUT STD_LOGIC;
    mat_5_we0 : OUT STD_LOGIC;
    mat_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_5_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_5_ce1 : OUT STD_LOGIC;
    mat_5_we1 : OUT STD_LOGIC;
    mat_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_6_ce0 : OUT STD_LOGIC;
    mat_6_we0 : OUT STD_LOGIC;
    mat_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_6_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_6_ce1 : OUT STD_LOGIC;
    mat_6_we1 : OUT STD_LOGIC;
    mat_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_7_ce0 : OUT STD_LOGIC;
    mat_7_we0 : OUT STD_LOGIC;
    mat_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_7_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_7_ce1 : OUT STD_LOGIC;
    mat_7_we1 : OUT STD_LOGIC;
    mat_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_8_ce0 : OUT STD_LOGIC;
    mat_8_we0 : OUT STD_LOGIC;
    mat_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_8_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_8_ce1 : OUT STD_LOGIC;
    mat_8_we1 : OUT STD_LOGIC;
    mat_8_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    lower_sum : IN STD_LOGIC_VECTOR (31 downto 0);
    upper_sum : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of makeZero is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln49_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_1222 : STD_LOGIC_VECTOR (0 downto 0);
    signal mat_1_addr_gep_fu_325_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_2_addr_gep_fu_334_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_3_addr_gep_fu_343_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_4_addr_gep_fu_352_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_5_addr_gep_fu_361_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_gep_fu_370_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_gep_fu_379_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_gep_fu_388_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_2_addr_9_gep_fu_397_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_3_addr_9_gep_fu_406_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_4_addr_9_gep_fu_415_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_5_addr_9_gep_fu_424_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_9_gep_fu_433_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_9_gep_fu_442_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_9_gep_fu_451_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mat_3_addr_10_gep_fu_622_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_4_addr_10_gep_fu_631_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_5_addr_10_gep_fu_640_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_10_gep_fu_649_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_10_gep_fu_658_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_10_gep_fu_667_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_4_addr_11_gep_fu_676_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_5_addr_11_gep_fu_685_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_11_gep_fu_694_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_11_gep_fu_703_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_11_gep_fu_712_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal mat_5_addr_12_gep_fu_883_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_12_gep_fu_892_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_12_gep_fu_901_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_12_gep_fu_910_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_6_addr_13_gep_fu_919_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_7_addr_13_gep_fu_928_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_13_gep_fu_937_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal mat_7_addr_14_gep_fu_1108_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_14_gep_fu_1117_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mat_8_addr_15_gep_fu_1126_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                icmp_ln49_reg_1222 <= icmp_ln49_fu_1216_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln49_fu_1216_p2 <= "1" when (signed(lower_sum) > signed(upper_sum)) else "0";

    mat_0_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_0_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_0_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_0_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_0_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mat_0_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_0_address0 <= "XXXX";
        end if; 
    end process;


    mat_0_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_0_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_0_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_0_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mat_0_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_0_address1 <= "XXXX";
        end if; 
    end process;


    mat_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mat_0_ce0 <= ap_const_logic_1;
        else 
            mat_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_0_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mat_0_ce1 <= ap_const_logic_1;
        else 
            mat_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_0_d0 <= ap_const_lv32_0;
    mat_0_d1 <= ap_const_lv32_0;

    mat_0_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_0_we0 <= ap_const_logic_1;
        else 
            mat_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_0_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_0_we1 <= ap_const_logic_1;
        else 
            mat_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_1_addr_gep_fu_325_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_1_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, mat_1_addr_gep_fu_325_p3, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_1_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_1_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_1_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_1_address0 <= mat_1_addr_gep_fu_325_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_1_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_1_address0 <= "XXXX";
        end if; 
    end process;


    mat_1_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_1_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_1_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_1_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_1_address1 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            mat_1_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_1_address1 <= "XXXX";
        end if; 
    end process;


    mat_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)))) then 
            mat_1_ce0 <= ap_const_logic_1;
        else 
            mat_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_1_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            mat_1_ce1 <= ap_const_logic_1;
        else 
            mat_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_1_d0 <= ap_const_lv32_0;
    mat_1_d1 <= ap_const_lv32_0;

    mat_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_1_we0 <= ap_const_logic_1;
        else 
            mat_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_1_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_1_we1 <= ap_const_logic_1;
        else 
            mat_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_2_addr_9_gep_fu_397_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_2_addr_gep_fu_334_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_2_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, mat_2_addr_gep_fu_334_p3, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_2_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_2_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_2_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_2_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_2_address0 <= mat_2_addr_gep_fu_334_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_2_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_2_address0 <= "XXXX";
        end if; 
    end process;


    mat_2_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, mat_2_addr_9_gep_fu_397_p3, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_2_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_2_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_2_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_2_address1 <= mat_2_addr_9_gep_fu_397_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_2_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_2_address1 <= "XXXX";
        end if; 
    end process;


    mat_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)))) then 
            mat_2_ce0 <= ap_const_logic_1;
        else 
            mat_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_2_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)))) then 
            mat_2_ce1 <= ap_const_logic_1;
        else 
            mat_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_2_d0 <= ap_const_lv32_0;
    mat_2_d1 <= ap_const_lv32_0;

    mat_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_2_we0 <= ap_const_logic_1;
        else 
            mat_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_2_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_2_we1 <= ap_const_logic_1;
        else 
            mat_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_3_addr_10_gep_fu_622_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_3_addr_9_gep_fu_406_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_3_addr_gep_fu_343_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_3_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_3_addr_gep_fu_343_p3, ap_CS_fsm_state2, mat_3_addr_10_gep_fu_622_p3, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_3_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_3_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_3_address0 <= mat_3_addr_10_gep_fu_622_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_3_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_3_address0 <= mat_3_addr_gep_fu_343_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_3_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_3_address0 <= "XXXX";
        end if; 
    end process;


    mat_3_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, mat_3_addr_9_gep_fu_406_p3, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_3_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_3_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_3_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            mat_3_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_3_address1 <= mat_3_addr_9_gep_fu_406_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_3_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_3_address1 <= "XXXX";
        end if; 
    end process;


    mat_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_3_ce0 <= ap_const_logic_1;
        else 
            mat_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_3_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)))) then 
            mat_3_ce1 <= ap_const_logic_1;
        else 
            mat_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_3_d0 <= ap_const_lv32_0;
    mat_3_d1 <= ap_const_lv32_0;

    mat_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_3_we0 <= ap_const_logic_1;
        else 
            mat_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_3_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_3_we1 <= ap_const_logic_1;
        else 
            mat_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_4_addr_10_gep_fu_631_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_4_addr_11_gep_fu_676_p3 <= ap_const_lv64_3(4 - 1 downto 0);
    mat_4_addr_9_gep_fu_415_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_4_addr_gep_fu_352_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_4_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_4_addr_gep_fu_352_p3, ap_CS_fsm_state2, mat_4_addr_10_gep_fu_631_p3, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_4_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_4_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_4_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_4_address0 <= mat_4_addr_10_gep_fu_631_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_4_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_4_address0 <= mat_4_addr_gep_fu_352_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_4_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_4_address0 <= "XXXX";
        end if; 
    end process;


    mat_4_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_4_addr_9_gep_fu_415_p3, ap_CS_fsm_state2, mat_4_addr_11_gep_fu_676_p3, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_4_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_4_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_4_address1 <= mat_4_addr_11_gep_fu_676_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_4_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_4_address1 <= mat_4_addr_9_gep_fu_415_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_4_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_4_address1 <= "XXXX";
        end if; 
    end process;


    mat_4_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_4_ce0 <= ap_const_logic_1;
        else 
            mat_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_4_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_4_ce1 <= ap_const_logic_1;
        else 
            mat_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_4_d0 <= ap_const_lv32_0;
    mat_4_d1 <= ap_const_lv32_0;

    mat_4_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_4_we0 <= ap_const_logic_1;
        else 
            mat_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_4_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_4_we1 <= ap_const_logic_1;
        else 
            mat_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_5_addr_10_gep_fu_640_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_5_addr_11_gep_fu_685_p3 <= ap_const_lv64_3(4 - 1 downto 0);
    mat_5_addr_12_gep_fu_883_p3 <= ap_const_lv64_4(4 - 1 downto 0);
    mat_5_addr_9_gep_fu_424_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_5_addr_gep_fu_361_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_5_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_5_addr_gep_fu_361_p3, ap_CS_fsm_state2, mat_5_addr_10_gep_fu_640_p3, ap_CS_fsm_state3, mat_5_addr_12_gep_fu_883_p3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_5_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_5_address0 <= mat_5_addr_12_gep_fu_883_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_5_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_5_address0 <= mat_5_addr_10_gep_fu_640_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_5_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_5_address0 <= mat_5_addr_gep_fu_361_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_5_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_5_address0 <= "XXXX";
        end if; 
    end process;


    mat_5_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_5_addr_9_gep_fu_424_p3, ap_CS_fsm_state2, mat_5_addr_11_gep_fu_685_p3, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_5_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_5_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_5_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_5_address1 <= mat_5_addr_11_gep_fu_685_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_5_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_5_address1 <= mat_5_addr_9_gep_fu_424_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_5_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_5_address1 <= "XXXX";
        end if; 
    end process;


    mat_5_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_5_ce0 <= ap_const_logic_1;
        else 
            mat_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_5_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_5_ce1 <= ap_const_logic_1;
        else 
            mat_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_5_d0 <= ap_const_lv32_0;
    mat_5_d1 <= ap_const_lv32_0;

    mat_5_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_5_we0 <= ap_const_logic_1;
        else 
            mat_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_5_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_5_we1 <= ap_const_logic_1;
        else 
            mat_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_6_addr_10_gep_fu_649_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_6_addr_11_gep_fu_694_p3 <= ap_const_lv64_3(4 - 1 downto 0);
    mat_6_addr_12_gep_fu_892_p3 <= ap_const_lv64_4(4 - 1 downto 0);
    mat_6_addr_13_gep_fu_919_p3 <= ap_const_lv64_5(4 - 1 downto 0);
    mat_6_addr_9_gep_fu_433_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_6_addr_gep_fu_370_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_6_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_6_addr_gep_fu_370_p3, ap_CS_fsm_state2, mat_6_addr_10_gep_fu_649_p3, ap_CS_fsm_state3, mat_6_addr_12_gep_fu_892_p3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_6_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_6_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_6_address0 <= mat_6_addr_12_gep_fu_892_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_6_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_6_address0 <= mat_6_addr_10_gep_fu_649_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_6_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_6_address0 <= mat_6_addr_gep_fu_370_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_6_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_6_address0 <= "XXXX";
        end if; 
    end process;


    mat_6_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_6_addr_9_gep_fu_433_p3, ap_CS_fsm_state2, mat_6_addr_11_gep_fu_694_p3, ap_CS_fsm_state3, mat_6_addr_13_gep_fu_919_p3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_6_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_6_address1 <= mat_6_addr_13_gep_fu_919_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_6_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_6_address1 <= mat_6_addr_11_gep_fu_694_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_6_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_6_address1 <= mat_6_addr_9_gep_fu_433_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_6_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_6_address1 <= "XXXX";
        end if; 
    end process;


    mat_6_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_6_ce0 <= ap_const_logic_1;
        else 
            mat_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_6_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_6_ce1 <= ap_const_logic_1;
        else 
            mat_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_6_d0 <= ap_const_lv32_0;
    mat_6_d1 <= ap_const_lv32_0;

    mat_6_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_6_we0 <= ap_const_logic_1;
        else 
            mat_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_6_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_6_we1 <= ap_const_logic_1;
        else 
            mat_6_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_7_addr_10_gep_fu_658_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_7_addr_11_gep_fu_703_p3 <= ap_const_lv64_3(4 - 1 downto 0);
    mat_7_addr_12_gep_fu_901_p3 <= ap_const_lv64_4(4 - 1 downto 0);
    mat_7_addr_13_gep_fu_928_p3 <= ap_const_lv64_5(4 - 1 downto 0);
    mat_7_addr_14_gep_fu_1108_p3 <= ap_const_lv64_6(4 - 1 downto 0);
    mat_7_addr_9_gep_fu_442_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_7_addr_gep_fu_379_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_7_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_7_addr_gep_fu_379_p3, ap_CS_fsm_state2, mat_7_addr_10_gep_fu_658_p3, ap_CS_fsm_state3, mat_7_addr_12_gep_fu_901_p3, ap_CS_fsm_state4, mat_7_addr_14_gep_fu_1108_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_7_address0 <= mat_7_addr_14_gep_fu_1108_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_7_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_7_address0 <= mat_7_addr_12_gep_fu_901_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_7_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_7_address0 <= mat_7_addr_10_gep_fu_658_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_7_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_7_address0 <= mat_7_addr_gep_fu_379_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_7_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_7_address0 <= "XXXX";
        end if; 
    end process;


    mat_7_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_7_addr_9_gep_fu_442_p3, ap_CS_fsm_state2, mat_7_addr_11_gep_fu_703_p3, ap_CS_fsm_state3, mat_7_addr_13_gep_fu_928_p3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_7_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            mat_7_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_7_address1 <= mat_7_addr_13_gep_fu_928_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_7_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_7_address1 <= mat_7_addr_11_gep_fu_703_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_7_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_7_address1 <= mat_7_addr_9_gep_fu_442_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_7_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_7_address1 <= "XXXX";
        end if; 
    end process;


    mat_7_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_7_ce0 <= ap_const_logic_1;
        else 
            mat_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_7_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_7_ce1 <= ap_const_logic_1;
        else 
            mat_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_7_d0 <= ap_const_lv32_0;
    mat_7_d1 <= ap_const_lv32_0;

    mat_7_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_7_we0 <= ap_const_logic_1;
        else 
            mat_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_7_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_7_we1 <= ap_const_logic_1;
        else 
            mat_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_8_addr_10_gep_fu_667_p3 <= ap_const_lv64_2(4 - 1 downto 0);
    mat_8_addr_11_gep_fu_712_p3 <= ap_const_lv64_3(4 - 1 downto 0);
    mat_8_addr_12_gep_fu_910_p3 <= ap_const_lv64_4(4 - 1 downto 0);
    mat_8_addr_13_gep_fu_937_p3 <= ap_const_lv64_5(4 - 1 downto 0);
    mat_8_addr_14_gep_fu_1117_p3 <= ap_const_lv64_6(4 - 1 downto 0);
    mat_8_addr_15_gep_fu_1126_p3 <= ap_const_lv64_7(4 - 1 downto 0);
    mat_8_addr_9_gep_fu_451_p3 <= ap_const_lv64_1(4 - 1 downto 0);
    mat_8_addr_gep_fu_388_p3 <= ap_const_lv64_0(4 - 1 downto 0);

    mat_8_address0_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_8_addr_gep_fu_388_p3, ap_CS_fsm_state2, mat_8_addr_10_gep_fu_667_p3, ap_CS_fsm_state3, mat_8_addr_12_gep_fu_910_p3, ap_CS_fsm_state4, mat_8_addr_14_gep_fu_1117_p3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_8_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address0 <= mat_8_addr_14_gep_fu_1117_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address0 <= mat_8_addr_12_gep_fu_910_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address0 <= mat_8_addr_10_gep_fu_667_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_8_address0 <= mat_8_addr_gep_fu_388_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_8_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            mat_8_address0 <= "XXXX";
        end if; 
    end process;


    mat_8_address1_assign_proc : process(ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, mat_8_addr_9_gep_fu_451_p3, ap_CS_fsm_state2, mat_8_addr_11_gep_fu_712_p3, ap_CS_fsm_state3, mat_8_addr_13_gep_fu_937_p3, ap_CS_fsm_state4, mat_8_addr_15_gep_fu_1126_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address1 <= mat_8_addr_15_gep_fu_1126_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address1 <= mat_8_addr_13_gep_fu_937_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1))) then 
            mat_8_address1 <= mat_8_addr_11_gep_fu_712_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0))) then 
            mat_8_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1))) then 
            mat_8_address1 <= mat_8_addr_9_gep_fu_451_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0))) then 
            mat_8_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            mat_8_address1 <= "XXXX";
        end if; 
    end process;


    mat_8_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_8_ce0 <= ap_const_logic_1;
        else 
            mat_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_8_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_8_ce1 <= ap_const_logic_1;
        else 
            mat_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    mat_8_d0 <= ap_const_lv32_0;
    mat_8_d1 <= ap_const_lv32_0;

    mat_8_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_8_we0 <= ap_const_logic_1;
        else 
            mat_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_8_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln49_fu_1216_p2, icmp_ln49_reg_1222, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_1) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (icmp_ln49_fu_1216_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln49_reg_1222 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln49_reg_1222 = ap_const_lv1_0)))) then 
            mat_8_we1 <= ap_const_logic_1;
        else 
            mat_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
