// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module makeZero (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_0_address0,
        mat_0_ce0,
        mat_0_we0,
        mat_0_d0,
        mat_0_address1,
        mat_0_ce1,
        mat_0_we1,
        mat_0_d1,
        mat_1_address0,
        mat_1_ce0,
        mat_1_we0,
        mat_1_d0,
        mat_1_address1,
        mat_1_ce1,
        mat_1_we1,
        mat_1_d1,
        mat_2_address0,
        mat_2_ce0,
        mat_2_we0,
        mat_2_d0,
        mat_2_address1,
        mat_2_ce1,
        mat_2_we1,
        mat_2_d1,
        mat_3_address0,
        mat_3_ce0,
        mat_3_we0,
        mat_3_d0,
        mat_3_address1,
        mat_3_ce1,
        mat_3_we1,
        mat_3_d1,
        mat_4_address0,
        mat_4_ce0,
        mat_4_we0,
        mat_4_d0,
        mat_4_address1,
        mat_4_ce1,
        mat_4_we1,
        mat_4_d1,
        mat_5_address0,
        mat_5_ce0,
        mat_5_we0,
        mat_5_d0,
        mat_5_address1,
        mat_5_ce1,
        mat_5_we1,
        mat_5_d1,
        mat_6_address0,
        mat_6_ce0,
        mat_6_we0,
        mat_6_d0,
        mat_6_address1,
        mat_6_ce1,
        mat_6_we1,
        mat_6_d1,
        mat_7_address0,
        mat_7_ce0,
        mat_7_we0,
        mat_7_d0,
        mat_7_address1,
        mat_7_ce1,
        mat_7_we1,
        mat_7_d1,
        mat_8_address0,
        mat_8_ce0,
        mat_8_we0,
        mat_8_d0,
        mat_8_address1,
        mat_8_ce1,
        mat_8_we1,
        mat_8_d1,
        lower_sum,
        upper_sum
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] mat_0_address0;
output   mat_0_ce0;
output   mat_0_we0;
output  [31:0] mat_0_d0;
output  [3:0] mat_0_address1;
output   mat_0_ce1;
output   mat_0_we1;
output  [31:0] mat_0_d1;
output  [3:0] mat_1_address0;
output   mat_1_ce0;
output   mat_1_we0;
output  [31:0] mat_1_d0;
output  [3:0] mat_1_address1;
output   mat_1_ce1;
output   mat_1_we1;
output  [31:0] mat_1_d1;
output  [3:0] mat_2_address0;
output   mat_2_ce0;
output   mat_2_we0;
output  [31:0] mat_2_d0;
output  [3:0] mat_2_address1;
output   mat_2_ce1;
output   mat_2_we1;
output  [31:0] mat_2_d1;
output  [3:0] mat_3_address0;
output   mat_3_ce0;
output   mat_3_we0;
output  [31:0] mat_3_d0;
output  [3:0] mat_3_address1;
output   mat_3_ce1;
output   mat_3_we1;
output  [31:0] mat_3_d1;
output  [3:0] mat_4_address0;
output   mat_4_ce0;
output   mat_4_we0;
output  [31:0] mat_4_d0;
output  [3:0] mat_4_address1;
output   mat_4_ce1;
output   mat_4_we1;
output  [31:0] mat_4_d1;
output  [3:0] mat_5_address0;
output   mat_5_ce0;
output   mat_5_we0;
output  [31:0] mat_5_d0;
output  [3:0] mat_5_address1;
output   mat_5_ce1;
output   mat_5_we1;
output  [31:0] mat_5_d1;
output  [3:0] mat_6_address0;
output   mat_6_ce0;
output   mat_6_we0;
output  [31:0] mat_6_d0;
output  [3:0] mat_6_address1;
output   mat_6_ce1;
output   mat_6_we1;
output  [31:0] mat_6_d1;
output  [3:0] mat_7_address0;
output   mat_7_ce0;
output   mat_7_we0;
output  [31:0] mat_7_d0;
output  [3:0] mat_7_address1;
output   mat_7_ce1;
output   mat_7_we1;
output  [31:0] mat_7_d1;
output  [3:0] mat_8_address0;
output   mat_8_ce0;
output   mat_8_we0;
output  [31:0] mat_8_d0;
output  [3:0] mat_8_address1;
output   mat_8_ce1;
output   mat_8_we1;
output  [31:0] mat_8_d1;
input  [31:0] lower_sum;
input  [31:0] upper_sum;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] mat_0_address0;
reg mat_0_ce0;
reg mat_0_we0;
reg[3:0] mat_0_address1;
reg mat_0_ce1;
reg mat_0_we1;
reg[3:0] mat_1_address0;
reg mat_1_ce0;
reg mat_1_we0;
reg[3:0] mat_1_address1;
reg mat_1_ce1;
reg mat_1_we1;
reg[3:0] mat_2_address0;
reg mat_2_ce0;
reg mat_2_we0;
reg[3:0] mat_2_address1;
reg mat_2_ce1;
reg mat_2_we1;
reg[3:0] mat_3_address0;
reg mat_3_ce0;
reg mat_3_we0;
reg[3:0] mat_3_address1;
reg mat_3_ce1;
reg mat_3_we1;
reg[3:0] mat_4_address0;
reg mat_4_ce0;
reg mat_4_we0;
reg[3:0] mat_4_address1;
reg mat_4_ce1;
reg mat_4_we1;
reg[3:0] mat_5_address0;
reg mat_5_ce0;
reg mat_5_we0;
reg[3:0] mat_5_address1;
reg mat_5_ce1;
reg mat_5_we1;
reg[3:0] mat_6_address0;
reg mat_6_ce0;
reg mat_6_we0;
reg[3:0] mat_6_address1;
reg mat_6_ce1;
reg mat_6_we1;
reg[3:0] mat_7_address0;
reg mat_7_ce0;
reg mat_7_we0;
reg[3:0] mat_7_address1;
reg mat_7_ce1;
reg mat_7_we1;
reg[3:0] mat_8_address0;
reg mat_8_ce0;
reg mat_8_we0;
reg[3:0] mat_8_address1;
reg mat_8_ce1;
reg mat_8_we1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln49_fu_1216_p2;
reg   [0:0] icmp_ln49_reg_1222;
wire   [3:0] mat_1_addr_gep_fu_325_p3;
wire   [3:0] mat_2_addr_gep_fu_334_p3;
wire   [3:0] mat_3_addr_gep_fu_343_p3;
wire   [3:0] mat_4_addr_gep_fu_352_p3;
wire   [3:0] mat_5_addr_gep_fu_361_p3;
wire   [3:0] mat_6_addr_gep_fu_370_p3;
wire   [3:0] mat_7_addr_gep_fu_379_p3;
wire   [3:0] mat_8_addr_gep_fu_388_p3;
wire   [3:0] mat_2_addr_9_gep_fu_397_p3;
wire   [3:0] mat_3_addr_9_gep_fu_406_p3;
wire   [3:0] mat_4_addr_9_gep_fu_415_p3;
wire   [3:0] mat_5_addr_9_gep_fu_424_p3;
wire   [3:0] mat_6_addr_9_gep_fu_433_p3;
wire   [3:0] mat_7_addr_9_gep_fu_442_p3;
wire   [3:0] mat_8_addr_9_gep_fu_451_p3;
wire    ap_CS_fsm_state2;
wire   [3:0] mat_3_addr_10_gep_fu_622_p3;
wire   [3:0] mat_4_addr_10_gep_fu_631_p3;
wire   [3:0] mat_5_addr_10_gep_fu_640_p3;
wire   [3:0] mat_6_addr_10_gep_fu_649_p3;
wire   [3:0] mat_7_addr_10_gep_fu_658_p3;
wire   [3:0] mat_8_addr_10_gep_fu_667_p3;
wire   [3:0] mat_4_addr_11_gep_fu_676_p3;
wire   [3:0] mat_5_addr_11_gep_fu_685_p3;
wire   [3:0] mat_6_addr_11_gep_fu_694_p3;
wire   [3:0] mat_7_addr_11_gep_fu_703_p3;
wire   [3:0] mat_8_addr_11_gep_fu_712_p3;
wire    ap_CS_fsm_state3;
wire   [3:0] mat_5_addr_12_gep_fu_883_p3;
wire   [3:0] mat_6_addr_12_gep_fu_892_p3;
wire   [3:0] mat_7_addr_12_gep_fu_901_p3;
wire   [3:0] mat_8_addr_12_gep_fu_910_p3;
wire   [3:0] mat_6_addr_13_gep_fu_919_p3;
wire   [3:0] mat_7_addr_13_gep_fu_928_p3;
wire   [3:0] mat_8_addr_13_gep_fu_937_p3;
wire    ap_CS_fsm_state4;
wire   [3:0] mat_7_addr_14_gep_fu_1108_p3;
wire   [3:0] mat_8_addr_14_gep_fu_1117_p3;
wire   [3:0] mat_8_addr_15_gep_fu_1126_p3;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        icmp_ln49_reg_1222 <= icmp_ln49_fu_1216_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_0_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_0_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_0_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        mat_0_address0 = 64'd0;
    end else begin
        mat_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_0_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_0_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_0_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        mat_0_address1 = 64'd1;
    end else begin
        mat_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        mat_0_ce0 = 1'b1;
    end else begin
        mat_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        mat_0_ce1 = 1'b1;
    end else begin
        mat_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_0_we0 = 1'b1;
    end else begin
        mat_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_0_we1 = 1'b1;
    end else begin
        mat_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_1_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_1_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_1_address0 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_1_address0 = mat_1_addr_gep_fu_325_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_1_address0 = 64'd0;
    end else begin
        mat_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_1_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_1_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_1_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        mat_1_address1 = 64'd1;
    end else begin
        mat_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        mat_1_ce0 = 1'b1;
    end else begin
        mat_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        mat_1_ce1 = 1'b1;
    end else begin
        mat_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_1_we0 = 1'b1;
    end else begin
        mat_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_1_we1 = 1'b1;
    end else begin
        mat_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_2_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_2_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_2_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_2_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_2_address0 = mat_2_addr_gep_fu_334_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_2_address0 = 64'd0;
    end else begin
        mat_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_2_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_2_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_2_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_2_address1 = mat_2_addr_9_gep_fu_397_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_2_address1 = 64'd1;
    end else begin
        mat_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        mat_2_ce0 = 1'b1;
    end else begin
        mat_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        mat_2_ce1 = 1'b1;
    end else begin
        mat_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_2_we0 = 1'b1;
    end else begin
        mat_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_2_we1 = 1'b1;
    end else begin
        mat_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_3_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_3_address0 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_3_address0 = mat_3_addr_10_gep_fu_622_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_3_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_3_address0 = mat_3_addr_gep_fu_343_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_3_address0 = 64'd0;
    end else begin
        mat_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_3_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_3_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_3_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_3_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_3_address1 = mat_3_addr_9_gep_fu_406_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_3_address1 = 64'd1;
    end else begin
        mat_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_3_ce0 = 1'b1;
    end else begin
        mat_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)))) begin
        mat_3_ce1 = 1'b1;
    end else begin
        mat_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_3_we0 = 1'b1;
    end else begin
        mat_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_3_we1 = 1'b1;
    end else begin
        mat_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_4_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_4_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_4_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_4_address0 = mat_4_addr_10_gep_fu_631_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_4_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_4_address0 = mat_4_addr_gep_fu_352_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_4_address0 = 64'd0;
    end else begin
        mat_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_4_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_4_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_4_address1 = mat_4_addr_11_gep_fu_676_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_4_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_4_address1 = mat_4_addr_9_gep_fu_415_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_4_address1 = 64'd1;
    end else begin
        mat_4_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_4_ce0 = 1'b1;
    end else begin
        mat_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_4_ce1 = 1'b1;
    end else begin
        mat_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_4_we0 = 1'b1;
    end else begin
        mat_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_4_we1 = 1'b1;
    end else begin
        mat_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_5_address0 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_5_address0 = mat_5_addr_12_gep_fu_883_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_5_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_5_address0 = mat_5_addr_10_gep_fu_640_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_5_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_5_address0 = mat_5_addr_gep_fu_361_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_5_address0 = 64'd0;
    end else begin
        mat_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_5_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_5_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_5_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_5_address1 = mat_5_addr_11_gep_fu_685_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_5_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_5_address1 = mat_5_addr_9_gep_fu_424_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_5_address1 = 64'd1;
    end else begin
        mat_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_5_ce0 = 1'b1;
    end else begin
        mat_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_5_ce1 = 1'b1;
    end else begin
        mat_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_5_we0 = 1'b1;
    end else begin
        mat_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_5_we1 = 1'b1;
    end else begin
        mat_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_6_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_6_address0 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_6_address0 = mat_6_addr_12_gep_fu_892_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_6_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_6_address0 = mat_6_addr_10_gep_fu_649_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_6_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_6_address0 = mat_6_addr_gep_fu_370_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_6_address0 = 64'd0;
    end else begin
        mat_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_6_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_6_address1 = mat_6_addr_13_gep_fu_919_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_6_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_6_address1 = mat_6_addr_11_gep_fu_694_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_6_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_6_address1 = mat_6_addr_9_gep_fu_433_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_6_address1 = 64'd1;
    end else begin
        mat_6_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_6_ce0 = 1'b1;
    end else begin
        mat_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_6_ce1 = 1'b1;
    end else begin
        mat_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_6_we0 = 1'b1;
    end else begin
        mat_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_6_we1 = 1'b1;
    end else begin
        mat_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_7_address0 = mat_7_addr_14_gep_fu_1108_p3;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_7_address0 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_7_address0 = mat_7_addr_12_gep_fu_901_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_7_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_7_address0 = mat_7_addr_10_gep_fu_658_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_7_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_7_address0 = mat_7_addr_gep_fu_379_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_7_address0 = 64'd0;
    end else begin
        mat_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_7_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        mat_7_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_7_address1 = mat_7_addr_13_gep_fu_928_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_7_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_7_address1 = mat_7_addr_11_gep_fu_703_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_7_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_7_address1 = mat_7_addr_9_gep_fu_442_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_7_address1 = 64'd1;
    end else begin
        mat_7_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_7_ce0 = 1'b1;
    end else begin
        mat_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_7_ce1 = 1'b1;
    end else begin
        mat_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_7_we0 = 1'b1;
    end else begin
        mat_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_7_we1 = 1'b1;
    end else begin
        mat_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_8_address0 = 64'd8;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address0 = mat_8_addr_14_gep_fu_1117_p3;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address0 = 64'd6;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address0 = mat_8_addr_12_gep_fu_910_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address0 = 64'd4;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address0 = mat_8_addr_10_gep_fu_667_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address0 = 64'd2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_8_address0 = mat_8_addr_gep_fu_388_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_8_address0 = 64'd0;
    end else begin
        mat_8_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address1 = mat_8_addr_15_gep_fu_1126_p3;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address1 = 64'd7;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address1 = mat_8_addr_13_gep_fu_937_p3;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address1 = 64'd5;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1))) begin
        mat_8_address1 = mat_8_addr_11_gep_fu_712_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0))) begin
        mat_8_address1 = 64'd3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1))) begin
        mat_8_address1 = mat_8_addr_9_gep_fu_451_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0))) begin
        mat_8_address1 = 64'd1;
    end else begin
        mat_8_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_8_ce0 = 1'b1;
    end else begin
        mat_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_8_ce1 = 1'b1;
    end else begin
        mat_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_8_we0 = 1'b1;
    end else begin
        mat_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd1) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (icmp_ln49_fu_1216_p2 == 1'd0) & (ap_start == 1'b1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state4) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln49_reg_1222 == 1'd0)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln49_reg_1222 == 1'd0)))) begin
        mat_8_we1 = 1'b1;
    end else begin
        mat_8_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign icmp_ln49_fu_1216_p2 = (($signed(lower_sum) > $signed(upper_sum)) ? 1'b1 : 1'b0);

assign mat_0_d0 = 32'd0;

assign mat_0_d1 = 32'd0;

assign mat_1_addr_gep_fu_325_p3 = 64'd0;

assign mat_1_d0 = 32'd0;

assign mat_1_d1 = 32'd0;

assign mat_2_addr_9_gep_fu_397_p3 = 64'd1;

assign mat_2_addr_gep_fu_334_p3 = 64'd0;

assign mat_2_d0 = 32'd0;

assign mat_2_d1 = 32'd0;

assign mat_3_addr_10_gep_fu_622_p3 = 64'd2;

assign mat_3_addr_9_gep_fu_406_p3 = 64'd1;

assign mat_3_addr_gep_fu_343_p3 = 64'd0;

assign mat_3_d0 = 32'd0;

assign mat_3_d1 = 32'd0;

assign mat_4_addr_10_gep_fu_631_p3 = 64'd2;

assign mat_4_addr_11_gep_fu_676_p3 = 64'd3;

assign mat_4_addr_9_gep_fu_415_p3 = 64'd1;

assign mat_4_addr_gep_fu_352_p3 = 64'd0;

assign mat_4_d0 = 32'd0;

assign mat_4_d1 = 32'd0;

assign mat_5_addr_10_gep_fu_640_p3 = 64'd2;

assign mat_5_addr_11_gep_fu_685_p3 = 64'd3;

assign mat_5_addr_12_gep_fu_883_p3 = 64'd4;

assign mat_5_addr_9_gep_fu_424_p3 = 64'd1;

assign mat_5_addr_gep_fu_361_p3 = 64'd0;

assign mat_5_d0 = 32'd0;

assign mat_5_d1 = 32'd0;

assign mat_6_addr_10_gep_fu_649_p3 = 64'd2;

assign mat_6_addr_11_gep_fu_694_p3 = 64'd3;

assign mat_6_addr_12_gep_fu_892_p3 = 64'd4;

assign mat_6_addr_13_gep_fu_919_p3 = 64'd5;

assign mat_6_addr_9_gep_fu_433_p3 = 64'd1;

assign mat_6_addr_gep_fu_370_p3 = 64'd0;

assign mat_6_d0 = 32'd0;

assign mat_6_d1 = 32'd0;

assign mat_7_addr_10_gep_fu_658_p3 = 64'd2;

assign mat_7_addr_11_gep_fu_703_p3 = 64'd3;

assign mat_7_addr_12_gep_fu_901_p3 = 64'd4;

assign mat_7_addr_13_gep_fu_928_p3 = 64'd5;

assign mat_7_addr_14_gep_fu_1108_p3 = 64'd6;

assign mat_7_addr_9_gep_fu_442_p3 = 64'd1;

assign mat_7_addr_gep_fu_379_p3 = 64'd0;

assign mat_7_d0 = 32'd0;

assign mat_7_d1 = 32'd0;

assign mat_8_addr_10_gep_fu_667_p3 = 64'd2;

assign mat_8_addr_11_gep_fu_712_p3 = 64'd3;

assign mat_8_addr_12_gep_fu_910_p3 = 64'd4;

assign mat_8_addr_13_gep_fu_937_p3 = 64'd5;

assign mat_8_addr_14_gep_fu_1117_p3 = 64'd6;

assign mat_8_addr_15_gep_fu_1126_p3 = 64'd7;

assign mat_8_addr_9_gep_fu_451_p3 = 64'd1;

assign mat_8_addr_gep_fu_388_p3 = 64'd0;

assign mat_8_d0 = 32'd0;

assign mat_8_d1 = 32'd0;

endmodule //makeZero
